[build]
  base = "apps/web"
  command = "pnpm run build"
  publish = "apps/web/.output/public"

[functions]
  directory = "apps/web/.output/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/__render__"
  status = 200